In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/news.db")

df = pd.read_sql_query("SELECT title FROM news", conn)

print("Total data:", len(df))
df.head()

Total data: 1345

                                               title
0  Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, ...
1  AS Kirim Kapal Perang ke Selat Hormuz, Eks KSA...
2  Prabowo Bertemu Macron di Istana Elysee, Bahas...
3  Isi Chat Pelecehan Seksual 16 Mahasiswa Hukum ...
4  7 Keunggulan Oghab 44, Bandara Bawah Tanah Ira...

In [6]:
# Lihat semua kolom yang ada
cursor = conn.execute("PRAGMA table_info(news)")
print([row[1] for row in cursor.fetchall()])

['id', 'title', 'source', 'link', 'tanggal', 'description', 'guid']

## 🧹 Data Cleaning

In [2]:
import sys
import os
sys.path.append(os.path.abspath('..'))
from src.utils import clean_text, filter_short_words

# Daftar stopword bahasa Indonesia sederhana
stopwords = set(['yang', 'di', 'ke', 'dan', 'dari', 'untuk', 'pada', 'dengan', 'ini', 'itu', 'juga', 'dalam', 'akan', 'oleh', 'ada', 'tidak', 'bisa', 'saat', 'telah', 'atau'])

def remove_stopwords(text):
    return " ".join([w for w in text.split() if w not in stopwords])

# Proses Data Cleaning
df['cleaned_title'] = df['title'].apply(clean_text)
df['cleaned_title'] = df['cleaned_title'].apply(remove_stopwords)
df['cleaned_title'] = df['cleaned_title'].apply(filter_short_words)

print("Hasil Data Cleaning:")
df[['title', 'cleaned_title']].head()

Hasil Data Cleaning:

,title,cleaned_title
0,"Trump Nyinyir Lagi: Tolong Beritahu Paus Leo, ...",trump nyinyir lagi tolong beritahu paus iran b...
1,"AS Kirim Kapal Perang ke Selat Hormuz, Eks KSA...",kirim kapal perang selat hormuz ksal ungkap an...
2,"Prabowo Bertemu Macron di Istana Elysee, Bahas...",prabowo bertemu macron istana elysee bahas alu...
3,Isi Chat Pelecehan Seksual 16 Mahasiswa Hukum ...,chat pelecehan seksual mahasiswa hukum terungk...
4,"7 Keunggulan Oghab 44, Bandara Bawah Tanah Ira...",keunggulan oghab bandara bawah tanah iran ters...